version: "3.9"
services:
  backend:
    image: '#image'
    container_name: gadgetarium
    ports:
      - "80:2023"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 2023
      DATABASE_URL: jdbc:postgresql://database:5432/postgres
      DATABASE_USER: gadgetariumdbuser
      DATABASE_PASS: gadgetariumdb2023
  database:
    image: postgres:latest
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gadgetariumdbuser
      POSTGRES_PASSWORD: gadgetariumdb2023
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: